### ISSUE TITLE
Cannot add user_meta on user registration

### ISSUE THREAD

**Issue by paulando** [nicumicle/simple-jwt-login#1]
## Bug Description
Here is what user_meta I try to send and below is how the plugin sees it:

![postman](https://user-images.githubusercontent.com/10710126/120513997-7bf47200-c3d5-11eb-82b0-35c3cc195d45.png)

The problem is backslashes which make json_decode return null.
The image below is a part of the code (/wp-content/plugins/simple-jwt-login/src/modules/SimpleJWTLoginService.php) where I tried to debug the issue:

![plugin](https://user-images.githubusercontent.com/10710126/120514344-dbeb1880-c3d5-11eb-876c-849a772d3cf3.png)

Wrapping $_REQUEST['user_meta'] in stripslashes() fixes the issue.

## Environment
| PHP version                       | 7.4.18
| WordPress version                 | 5.7.2
| Simple-JWT-Login plugin version   | 2.6.2

**Comment by nicumicle** [comment]
Added a new plugin version ( 3.0.0 ). In this version, you can send the meta in body/request URI. If it is sent in URI, it checks to replace the `\"` and decode the JSON. Please try the new version, and if everything is working ok, we can close this issue.

**Comment by paulando** [comment]
Tested version 3.0.0 and can confirm that it works as expected. Great job and Thank You!
