### ISSUE TITLE
"simple_jwt_login_register_hook" and "simple_jwt_login_login_hook" returns $userId, not Wp_User $user

### ISSUE THREAD

**Issue by WDD-AS** [nicumicle/simple-jwt-login#10]
As described in the documentation, Wp_User $user should be returned. But only the $userId is returned. 

https://github.com/nicumicle/simple-jwt-login/blob/9929e15600730a628b53fe5e7702c016b0622896/simple-jwt-login/src/Services/RegisterUserService.php#L97-L107

**Comment by nicumicle** [comment]
Hello @WDD-AS,

Thank you for telling me about this bug. I fixed this bug, and the changes are already in `master`.
