### ISSUE TITLE
bug: Unable to get user profile data from API

### ISSUE THREAD

**Issue by DudeThatsErin** [nicumicle/simple-jwt-login#106]
# Bug Report

## Plugin Version
3.53.3

## PHP Version
8.1.27

## WordPress Version
6.5.2

## Bug description
I am trying to retrieve information from the wordpress database using the plugin like the user's name (first and last) and email to store in my secure storage for my app.

When I attempt to use the `validate JWT URL` address I get this error:
```
{"success":false,"data":{"message":"Unable to find user user property in JWT.( Settings: user.id )","errorCode":29}}
```
Because the data that is retrieved is this:
```
{"success":true,"data":{"jwt":"JWTTOKENHIDDEN"}}
```
I have the payload set up for everything correctly as far as I'm aware.

<img width="131" alt="Screenshot 2024-05-01 at 11 26 27 AM" src="https://github.com/nicumicle/simple-jwt-login/assets/2681022/ca2cf337-4eb1-4ba0-afd4-61794740245a">

## Other installed plugins (optional)
This is our development site and we make heavy use of plugins so we have a lot:

- BP Classic 1.4.0
- BuddyPress 12.4.1
- Custom User Notes (custom plugin that may be removed in the future) 1.0
- Export Contacts (custom plugin that is staying) 1.0
- G1 Socials 1.2.28
- GP Easy Passthrough 1.9.29
- GP Entry Blocks (disabled) 1.0-beta-1.2
- GP QR Code 1.0.10
- Gravity Forms 2.8.9
- Gravity Forms + Custom Post Types (disabled) 3.1.29
- Gravity Forms Advanced Post Creation Add-On 1.4.0
- Gravity Forms All Fields Template 0.10
- Gravity Forms Partial Entries Add-On 1.7
- Gravity Forms Signature Add-On 4.6.0
- Gravity Forms User Registration Add-On 5.3.0
- Gravity PDF 6.10.1
- Gravity Perks 2.36.6
- GravityExport 1.4.0
- GravityExport Lite 2.2.0
- GravityView 2.22
- Guest Author (disabled) 2.5
- miniOrange oAuth 2.0 Server/Provider (disabled) 6.0.5
- QR Connect (custom plugin that is staying) 1.0
- Snax 1.94
- Uncanny Automator 5.7.0.1
- Uncanny Automator 5.3
- Under Construction (disabled) 1.22
- WordPress REST API Authentication 3.2.0
- WP Mail SMTP 4.0.1

**Comment by nicumicle** [comment]
Hi @DudeThatsErin ,

The issue here is that you have set the wrong payload key for the JWT. 

Please go to  **Simple JWT Plugin settings** -> **Login** -> **JWT parameter key** and set it to "id" or "email" ( without the double quotes). 
![image](https://github.com/nicumicle/simple-jwt-login/assets/20170987/6f5e71d4-faef-401b-a851-87074a753516)


As I see in the error message, currently you set "user.id", but if you generate the JWT in the "/simple-jwt-login/v1/auth" endpoint, the payload will contain the following keys: id, email, username, site...

You can check your JWT payload on https://jwt.io/.

**Comment by DudeThatsErin** [comment]
Then why use `user.id` as an example if `user.id` doesn't work?

**Comment by nicumicle** [comment]
Now that you mentioned, i also see it very confusing. Most of the people generate JWT in the /auth endpoint. So definitely should be 'id' or 'email' .

**Comment by nicumicle** [comment]
I will close this issue. 

The UI has been improved. 
![image](https://github.com/nicumicle/simple-jwt-login/assets/20170987/d30dbc4f-9fb0-4537-a4db-e64e2a0e69b5)

**Comment by cgdmohamed** [comment]
i'm getting 
`{
	"success": false,
	"data": {
		"message": "WordPress User not found.",
		"errorCode": 54,
		"type": "simple-jwt-login-middleware"
	}
}`
