### ISSUE TITLE
Hi, can i reset the user password directly without passing the code

### ISSUE THREAD

**Issue by williampractice1** [nicumicle/simple-jwt-login#13]
## Is your feature request related to a problem?

i need to be able to change the user password but without providing a code
i dont need the user to go to its email
## Describe the solution you'd like
is there a way to retrieve this code via a request api
a posible solution instead of passing the code we can pass the jwt

## Additional context (optional)
 Thanks i hope to get a response and thank you so much

**Comment by nicumicle** [comment]
Hello @williampractice1,

You can now use a JWT in order to reset a user password. Instead of the reset password code, you can send a JWT.
In order to be able to use this feature, you need to check the option: `Allow Reset password with JWT` from the plugin settings.

Here is an example:
```
curl --location --request PUT 'http://localhost/?rest_route=/simple-jwt-login/v1/user/reset_password&email=email@email.com&new_password=123123&JWT=YOUR_JWT'
```

Let me know what do you think.

**Comment by epanganiban** [comment]
When can we expect this to be available in production?

**Comment by nicumicle** [comment]
Hello @epanganiban,
I'm planning to do a release tomorrow. I still need to so some checks. I will keep you posted.

**Comment by nicumicle** [comment]
Hello @epanganiban, 

New plugin version `3.4.1` has been released.

**Comment by epanganiban** [comment]
Wow... that was quick. Really appreciate the work you put into this plugin. Thanks @nicumicle.

**Comment by nicumicle** [comment]
hello @epanganiban,

When JWT is used, the plugin searches the key and type from *Login* settings. 

So, you need to make sure you have "Login by email" and "email".

Here is an example:
![image](https://user-images.githubusercontent.com/20170987/145012541-979d2931-ad8d-433f-8f1c-e4409b159ddc.png)


Let me know if this fixes your issue.

**Comment by epanganiban** [comment]
Yup. That definitely solves it. 

Since I had auto-login disabled I didn't even bother to look at 'Login' and spent most of my time on the 'Authentication' settings.

Thanks again.
