### ISSUE TITLE
Get a JWT on password reset

### ISSUE THREAD

**Issue by lejager** [nicumicle/simple-jwt-login#2]
Hey there, thanks for a great plugin!
I’ve searched the docs and support, and it looks like the only way to get a JWT via the rest api is by supplying a username and password. I’m trying to build a custom password reset flow, and I’m wondering if there’s any way to provide the username and password reset code, and get a JWT in response.

Thanks kindly for your time.

**Comment by nicumicle** [comment]
Hello @lejager,

The reset and change user password feature has just been released. You can find it in version 3.1.0.
