### ISSUE TITLE
Allow send body for /v1/auth api

### ISSUE THREAD

**Issue by IRediTOTO** [nicumicle/simple-jwt-login#22]
## Is your feature request related to a problem?
Yes, I am trying use api `/v1/auth` to authenticate but my password has special character. 
## Describe the solution you'd like
  Allow to send email/password in body

Thank you for made this pack :) best out there for now

**Comment by nicumicle** [comment]
Hello @IRediTOTO,

You can send the email and password in the body as a JSON. 

Here is an example:

**Register user**:
   ```
    curl -d '{"email":"test123@test123.com","password":"123!@#$%"}' -X POST http://localhost/?rest_route=/simple-jwt-login/v1/users
   ```

**Authenticate**:
  ```
  curl -d '{"email":"test123@test123.com","password":"123!@#$%"}' -X POST http://localhost/?rest_route=/simple-jwt-login/v1/auth 
  ```

Let me know if this works for you.

PS: Please make sure you use the latest plugin version. The support for JSON in body has been added in 3.0.0. ( https://github.com/nicumicle/simple-jwt-login/blob/master/Changelog.md#300-11-july-2021)

**Comment by IRediTOTO** [comment]
@nicumicle  THank you, I didn't know about it in docs, if you have time let's right some. Thank you again :D
