### ISSUE TITLE
Allow Users to make post

### ISSUE THREAD

**Issue by elmcapp** [nicumicle/simple-jwt-login#26]
1.) Is there any way to allow users to make post?
2.) Is this plugin mainly a user utility just to create, delete, change password, etc.  I see that there is a login and auto login feature it would be great to be able to create post using the rest api with your plugin

**Comment by dani3l3** [comment]
> 1.) Is there any way to allow users to make post? 2.) Is this plugin mainly a user utility just to create, delete, change password, etc. I see that there is a login and auto login feature it would be great to be able to create post using the rest api with your plugin


Creating a post sounds like another scenario altoghether that goes beyond the intended purpose of glueing systems's authentication to integrate various worlds.... but let's see what the author thinks :-)

**Comment by nicumicle** [comment]
You can call endpoints as authenticated users, by using the "All WordPress endpoints checks for JWT authentication" feature ( General ) :

![image](https://user-images.githubusercontent.com/20170987/151043681-2e431240-06ba-4d1a-a2df-5c0614f54e2c.png)

Here is a curl example of how you can create posts:

```
curl -X POST "http://localhost/wp-json/wp/v2/posts?content=PostContent&title=PostTitle" -d '{"JWT":"YOUR_JWT_HERE"}'
```

or 

```
curl -X POST "http://localhost/wp-json/wp/v2/posts" -H "Authorization: Bearer YOUR_JWT_HERE" --form title="Title" --form content="My content" --form type="page"
```

**Comment by dani3l3** [comment]
Very neat! I had not yet explored that new feature. 

As a side note (maybe off topic but as I am already writing...): Thanks for this wonderful plugin! It allowed us to quickly stand up a new set of scenarios and I am sure we will discover more of them in the next few months... I need to ask my boss if he would allow me to submit a small donation from the company's budget 🙄 😅😅👍💚🙏🙏
