### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by caldevcani** [nicumicle/simple-jwt-login#27]
## Bug Description
I am using axios to first get the token from the back end. Then I want to send the token back so I can log in and get the user that is logged in. I get a 400 error every time I send the token back. Someone on stackoverflow told me to check the token and i did and it says the signature is invalid. It maybe be a setting but the docs do not explain in detail what the settings must be so I don't know. I need to make this work but the docs does not explain in enough detail especially if you are not a seasoned developer like me.

What did you expect to happen? What actually happened?
Well I would like to be able to log in using Vue

## Environment

| Question                          | Answer
| ----------------------------------| -------
| PHP version                       | 7.4.1
| WordPress version                 | 5.9
| Simple-JWT-Login plugin version   | latest

## Other installed plugins (optional)
None no other plugins installed

**Comment by caldevcani** [comment]
Any help?

**Comment by Lupul** [comment]
@caldevcani  How did you fixed this? What settings had to be changed?

**Comment by caldevcani** [comment]
On the plugin page under the general tab at the bottom there are four settings make sure the top two are set to on
