### ISSUE TITLE
Passing user_meta in POST body doesn't work

### ISSUE THREAD

**Issue by Weeb** [nicumicle/simple-jwt-login#28]
First of all, thanks for a great plugin!

## Bug Description
Passing "user_meta" in POST body as JSON doesn't work, for example:

"user_meta": {
        "billing_first_name": "Billy-Bob",
        "billing_last_name": "Thornton"
}

However it works if passing it as a string via URL parameter, which can get quite messy if dealing with more meta.

I've managed to fix it by directly editing RegisterUserService.php (around line 77) and checking if 
$this->request['user_meta'] is an array before running json_decode.

## Environment

| Question                          | Answer
| ----------------------------------| -------
| PHP version                       | 7.4.10
| WordPress version                 | 5.9
| Simple-JWT-Login plugin version   | 3.4.2

## Additional Context (optional)

![image](https://user-images.githubusercontent.com/3097098/154637900-fff4a3ea-0419-45f6-b018-53ff2e5f6be1.png)

**Comment by Lupul** [comment]
I was able to reproduce this issue too, json in body is already decoded in ParseRequest.php:L51 https://github.com/nicumicle/simple-jwt-login/blob/aa4dd197c0a1c801bd160a2a0d2e6108e1393610/simple-jwt-login/src/Libraries/ParseRequest.php#L51
