### ISSUE TITLE
New users assigned `None` role

### ISSUE THREAD

**Issue by j-funk** [nicumicle/simple-jwt-login#3]
## Bug Description
When using register user api, the default role is ignored and they are assigned 'None' role.

## Environment

| Question                          | Answer
| ----------------------------------| -------
| PHP version                       | 7.4.16
| WordPress version                 | 5.7
| Simple-JWT-Login plugin version   | 2.6.2

To reproduce, just try to create a new user then check the role.  I had to edit the code manually in `SimpleJWTLoginService.php` on line 469:

```
		$user = $this->wordPressData->createUser(
			$username,
			$email,
			$password,
            'subscriber',
			$extraParameters
		);
```

**Comment by nicumicle** [comment]
I was able to reproduce this issue when I changed the default role to "Subscriber". 

So, in order to fix this, just change the default role name to `subscriber` (lower case).

**Comment by j-funk** [comment]
That's not the case, my role was set to `subscriber` lowercase.  I tried many things before I resorted to modifying the source.

**Comment by nicumicle** [comment]
I'm working now on version 3.0 for the plugin, and I've testes your scenario with this version. I will push it to github later today. If you have time, you can try with this new version.

Otherwise, if it will not work, i will have to investigate more.

**Comment by j-funk** [comment]
Thanks, I'm on vacation for the next week and a half, will definitely check it out when I return and let you know.

**Comment by j-funk** [comment]
Going to test this now, thanks for your work!  Much appreciated.

**Comment by j-funk** [comment]
I downloaded master and tested that my issue has been resolved.  Thanks again, great work.
