### ISSUE TITLE
Invalid code provided when trying to reset password

### ISSUE THREAD

**Issue by mathieuCatapulpe** [nicumicle/simple-jwt-login#31]
I am trying to reset users password but I always get errorCode : 62 "Invalid code provided", also I noticed the suggested route (in the wp admin plugin page) is using "user" instead of "users" like mentionned in the docs, but "users" leads to a 404 error, could it be related ?

my project is using vuejs/nuxt
```
      axios.put('https://top-drive21.catapulpe.fr/wp-json/simple-jwt-login/v1/user/reset_password', {
        "email": this.email,
        "code": this.code,
        "new_password": this.password,
      })
        .then( (response) => {
          console.log( response )
        })
        .catch((error) => {
          console.log(this.email)
          console.log(this.code)
          console.log(this.password)
          console.error( 'Error', error.response );
        });
```

**Comment by aduptive** [comment]
same here!

**Comment by OmarBochkati** [comment]
I encountered the same bug and to make it work I sent the user nickname in the email field and it worked. Definitely this is a bug but hope this helps

**Comment by nicumicle** [comment]
I found the issue. I'm preparing the fix.

**Comment by nicumicle** [comment]
I just pushed the fix. 

@mathieuCatapulpe  @aduptive @OmarBochkati Can one of you please download the plugin from https://github.com/nicumicle/simple-jwt-login/tree/master/download and check on your side?

Now it should find the user by email address.

**Comment by OmarBochkati** [comment]
@nicumicle Hi Nicu, thanks it works perfectly. I did a workaround myself in order not to get stuck but your fix does the trick. Thanks for the quick replies and fix

**Comment by nicumicle** [comment]
Thank you for checking @OmarBochkati !!
