### ISSUE TITLE
How can the user know the generated password when using the register API

### ISSUE THREAD

**Issue by slevy85** [nicumicle/simple-jwt-login#34]
## Is your feature request related to a problem?
No it is a question

## Describe the solution you'd like
I was expecting that the user would receive his password by email.

Hi, I have been able to register a user without sending a password, and I was expecting to get the generated password in some way but I couldn't find how, can you help me ?
Thank you very much

**Comment by nicumicle** [comment]
​Hello @slevy85 ,

This plugin does not send any email.
You can use the hooks to send the password to the user.
You can find an example in the documentation.

https://simplejwtlogin.com/docs/hooks#send-an-email-after-a-new-user-has-been-created

Let me know if this works ok for you.
