### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by elmcapp** [nicumicle/simple-jwt-login#37]
It seem as this plugin is causing issue with site not aways updating. It seem as I have to keep clear the cache. Is there a way to fix this or a way to make your plugin clear cache

**Comment by Lupul** [comment]
Not enough information provided imo, at least what caching plugin are you using and how did you singled out 'simple-jwt-login' plugin to be the one preventing cache invalidation?

**Comment by elmcapp** [comment]
I'm not using a caching plugin. The only plugin I am using is the Simple JWt..

**Comment by nicumicle** [comment]
Your WordPress hosting might cache the requests.

You can try one of these:
- add to your request `Cache-Control: no-cache` in the header
- add a dynamic parameter in the URL of the request(for example a timestamp): `&t=123455`

If still you have issues, can you send an example of how you make the request?
