### ISSUE TITLE
Sorry, you are not allowed to create posts as this user

### ISSUE THREAD

**Issue by elmcapp** [nicumicle/simple-jwt-login#39]
I am getting error:
Sorry, you are not allowed to create posts as this user
```
curl -X POST "https://cloud.elmc.app/wp-json/wp/v2/posts" -H "Authorization: Bearer I_Put_Real_JWT_Token_Here" --form title="Test Title" --form content="My test content" --form type="page"
```
<img width="1252" alt="Screen Shot 2022-05-05 at 8 15 19 AM" src="https://user-images.githubusercontent.com/64275658/166921268-523aed49-5181-446d-b257-262ea8dff07f.png">

**Comment by elmcapp** [comment]
I was able to get this to work by passing The JWT as a param or body. does not work when trying to pass The JWT in the header

**Comment by xitex** [comment]
> I was able to get this to work by passing The JWT as a param or body. does not work when trying to pass The JWT in the header

hi man, if you use email to login, try to fill "JWT parameter key | JWT payload data id (key name where the option is saved) *" on login section. And on Authentication section try to check all checkboxes on JWT Payload parameter, if this is not working try also on section Protect endpoints activate it for all endpoints
