### ISSUE TITLE
Can't pass jwt token in header using Axios

### ISSUE THREAD

**Issue by elmcapp** [nicumicle/simple-jwt-login#40]
Can't not pass The JWT token in the header

```
 const options = {
      method: "get",
      url: `${url}/wp-json/wp/v2/media`,
        headers: {
          Authorization: `Bearer ${token}`,
        },
      cancelToken: source.token,
    };

    axios(options)
```

The plugin does not see The JWT in the header. In the general tab I have header turn on with Authorization

This use to work on the prevous version

**Comment by Lupul** [comment]
Can you reproduce the problem using curl?
```bash
JWT="JWTKEY"
curl "https://domain.com/wp-json/wp/v2/media" -H "Authorization: Bearer $JWT" -v | jq
```
Also make sure you have "All WordPress endpoints checks for JWT authentication"  option checked on the "General" plugin settings page:
![image](https://user-images.githubusercontent.com/3596864/168467197-8d912385-5ce8-474e-97e5-35fe10ec695e.png)
