### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by bklein1979** [nicumicle/simple-jwt-login#46]
## Bug Description
When accessing WooCommerce on our site we are getting the following error above the products:

`Warning: Cannot modify header information - headers already sent by (output started at /homepages/36/d333902371/htdocs/newsite/wp-content/themes/covernews-pro/header.php:13) in /homepages/36/d333902371/htdocs/newsite/wp-content/plugins/simple-jwt-login/src/Helpers/CorsHelper.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /homepages/36/d333902371/htdocs/newsite/wp-content/themes/covernews-pro/header.php:13) in /homepages/36/d333902371/htdocs/newsite/wp-content/plugins/simple-jwt-login/src/Helpers/CorsHelper.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /homepages/36/d333902371/htdocs/newsite/wp-content/themes/covernews-pro/header.php:13) in /homepages/36/d333902371/htdocs/newsite/wp-content/plugins/simple-jwt-login/src/Helpers/CorsHelper.php on line 13`

These seem to correlate to the three options on the CORS page of the plugin, when removing one or more of the options the number of errors is reduced but still remains. The error looks to be due to conflicting code in covernews-pro theme.

## Environment

| Question                                          | Answer
| ---------------------------------------| -------
| PHP version                                      | 7.2.34
| WordPress version                           | 5.7.6
| Simple-JWT-Login plugin version   | 3.4.6

**Comment by nicumicle** [comment]
Hello @bklein1979 ,
I wrote this blog post on how you can set CORS on the server side. 
Check it here: https://simplejwtlogin.com/blog/cors-setup-apache

After doing that, you can disable the CORS from the plugin and everything should work ok.

Also, there might be an issue with the theme.

Hope this helps. I will close the issue for now, and re-open it in case that does not fix your issue.
