### ISSUE TITLE
Cannot pass '&' in password

### ISSUE THREAD

**Issue by adamwolfs** [nicumicle/simple-jwt-login#50]
I am attempting to do a PUT updating the password. What i've found is that if you put a & in the password it breaks. I have been unable to find anyway to encode it so that if you do so, it doesn't break. Looks to be a bug?

**Comment by nicumicle** [comment]
Can you please provide an example?

**Comment by nicumicle** [comment]
I was able to replicate this issue. I will provide a fix for this.

**Comment by nicumicle** [comment]
Hello @adamwolfs,

I've merged a fix for this issue.
Can you please test it also on your side that everything is working ok?

You can download the new version from here: https://github.com/nicumicle/simple-jwt-login/tree/master/download

Thank you.

**Comment by nicumicle** [comment]
```bash
curl -X POST http://localhost/wp-json/simple-jwt-login/v1/users -d '{"email":"test@mydomain.com","password":"123&!@"}'
```
