### ISSUE TITLE
Add labels to missing radio/inputs from the plugin

### ISSUE THREAD

**Issue by nicumicle** [nicumicle/simple-jwt-login#54]
This will allow us to select/deselect an option when the label is clicked. 
Also and will improve the user experience.

In most of the plugin code, there are labels already added, but there are some missing places.

Here is where we need to add new labels:
 - **General**:
     - All WordPress endpoints checks for JWT authentication
 - **Reset password**: 
     - Allow Reset password
     - Reset password requires Auth code
     
 - **Authentication**:
      - Authentication requires auth code
 - **CORS**
       - Access-Control-Allow-Origin
       - Access-Control-Allow-Methods
       - Access-Controle-Allow-Headers    

Example:

This is how it is now:
```
  <input type="checkbox" name="cors[allow_origin_enabled]" value="1" checked="">
        <b>Access-Control-Allow-Origin</b>
```

This is how it should be:

```
  <input type="checkbox" name="cors[allow_origin_enabled]" value="1" checked="" id="cors_allow_origin_enabled">
  <label for="cors_allow_origin_enabled">
              <b>Access-Control-Allow-Origin</b>
  </label>
```

**Comment by true2thepen** [comment]
@nicumicle Do you want the yes/no radio buttons changed to checkboxes?

**Comment by true2thepen** [comment]
From this:
![Screenshot_20221129_130415](https://user-images.githubusercontent.com/25501927/204612103-7f5dbc12-0bc7-40f7-b5de-6b3144a3b8ba.png)
To this:
![Screenshot_20221129_131025](https://user-images.githubusercontent.com/25501927/204612152-3456d830-c8b5-420c-8ca3-c76f8688f014.png)

**Comment by nicumicle** [comment]
> @nicumicle From this: ![Screenshot_20221129_130415](https://user-images.githubusercontent.com/25501927/204612103-7f5dbc12-0bc7-40f7-b5de-6b3144a3b8ba.png) To this: ![Screenshot_20221129_131025](https://user-images.githubusercontent.com/25501927/204612152-3456d830-c8b5-420c-8ca3-c76f8688f014.png)

Let's leave it like this for the moment, and create a new issue where we can change all the radio to checkboxes in all the sections.
