### ISSUE TITLE
Remove the "Beta" tag from General Settings

### ISSUE THREAD

**Issue by nicumicle** [nicumicle/simple-jwt-login#57]
Remove the "Beta" tag from "General" -> "All WordPress endpoints checks for JWT authentication"

It is added in views/general-view.php

We need to remove the `<span class="beta">beta</span>` and leave the option.

Also, clean up the CSS for beta (`#simple-jwt-login span.beta`).

**Currently, it looks like this:**
![image](https://user-images.githubusercontent.com/20170987/199903285-d67ab3de-219a-493b-8a82-35e48044a250.png)

**Desired Result:**
![image](https://user-images.githubusercontent.com/20170987/199903425-953d799b-2f78-47d6-838f-4bef9010b0d4.png)

**Comment by true2thepen** [comment]
I have removed the tag in my fork through https://github.com/true2thepen/simple-jwt-login/tree/true2thepen-patch-1. It has been tested on my test server running WP 6.1.1 and PHP 8.1.
![Screenshot_20221128_152619](https://user-images.githubusercontent.com/25501927/204374288-7e179f56-dcc2-49aa-884e-03caab6151d2.png)

**Comment by nicumicle** [comment]
Nice. Feel free to open a pull request. :partying_face:
