### ISSUE TITLE
bug: Missing before_endpoint hooks

### ISSUE THREAD

**Issue by giordanovi** [nicumicle/simple-jwt-login#60]
# Bug Report
Missing simple_jwt_login_before_endpoint

## Plugin Version
3.4.8

## PHP Version
8.1

## WordPress Version
6.1.1

## Bug description
I noticed that hooks are missing before authentication. The documentation (Hooks/Code examples) mentions the ability to use simple_jwt_login_before_endpoint but this doesn't work.
Using the code:

```
add_action('simple_jwt_login_before_endpoint', function($method, $endpoint, $request){
       if ($method !== 'POST' && $endpoint !== 'auth') {
          return;
       }
       
       if( isset($request['email']) && $request['email'] === 'test@domain.com') {
           throw new Exception('Wrong email.');
       }
}, 10, 4);
```

Nothing appens.
How can i solve?
Thanks

**Comment by nicumicle** [comment]
Hello @giordanovi,

The hooks are not triggered if they are not enabled from settings.

Is the hook enabled in the plugin settings? 

![image](https://user-images.githubusercontent.com/20170987/202670992-3ed9b419-b685-4a7f-a83a-b13fc723ca05.png)

**Comment by nicumicle** [comment]
Also, if you are using the plugin version from [WordPress.org](http://wordpress.org/plugins/simple-jwt-login/), then this feature is not included there.

Please check the [Changelog](https://github.com/nicumicle/simple-jwt-login/blob/master/Changelog.md) to see what we have released on wordpress.org.

This feature is available only for testing at the moment. You can download it from [https://simplejwtlogin.com/](https://simplejwtlogin.com/)

**Comment by giordanovi** [comment]
@nicumicle I've installed the plugin version from Wordpress.org and  this hook is not includued.
 Installing from github all works.
Thanks.
