### ISSUE TITLE
bug: If JWT parameter key is not set, validate, refresh token, etc. do not work. 

### ISSUE THREAD

**Issue by true2thepen** [nicumicle/simple-jwt-login#62]
# Bug Report

## Plugin Version
3.4.8

## PHP Version
8.1

## WordPress Version
6.1.1

## Bug description
If JWT parameter key is not set, validate, refresh token, etc. do not work.
Passes empty parameter to getUserParameterValueFromPayload. In the settings page for login adding a check to ensure that it is set would solve this problem. Possibly change error message in validate and refresh from
'Unable to find user %s property in JWT' to 'Ensure JWT parameter key is set in Login settings.'.

Once JWT parameter key is set, everything seems to work fine. I have not extensively tested all endpoints as that would be very time consuming. It does fix the problem with validate and refresh token.

**Comment by true2thepen** [comment]
Working. Error shows when jwt is not set. I'd call it fixed.

**Comment by nicumicle** [comment]
Thanks for checkjng @true2thepen!

I will alao close this issue.
