### ISSUE TITLE
WordPress update failure

### ISSUE THREAD

**Issue by true2thepen** [nicumicle/simple-jwt-login#64]
# Bug Report
WordPress uses the Rest API to perform certain actions. For example, updating posts. When protection for all endpoints is enabled it stops WordPress from accessing the Rest API.
## Plugin Version
3.4.8

## PHP Version
8.1

## WordPress Version
6.1.1

## Bug description
WordPress post update failed on updating posts. This happens on any post update. The problem being is that the plugin is preventing WordPress from accessing the Rest API. If you turn protection for all endpoints off WordPress can access. 

Having to turn protection off defeats the purpose of the plugin. Whitelisting the /wp/v2/posts endpoint solves the problem for WordPress. It however, also opens it  wide open to others. I'm wondering if there is a way to tell whether WordPress is the one accessing the Rest Api or if it's from an outside source. One possibility that comes to mind is to whitelist the ip address of WordPress - allowing it full access.

**Comment by true2thepen** [comment]
UPDATE: This only happens if you turn off both SESSION and COOKIE under the General Tab. I think that the solution maybe to just document this and possible add a warning that turn both off effectively stops WordPress from adding new Posts.

**Comment by nicumicle** [comment]
Helli @true2thepen,

I just pushed a possible fix for this issue. When you have time, cand you please check that is working on your side?

**Comment by true2thepen** [comment]
Was able to post with all endpoints protected.

**Comment by nicumicle** [comment]
Thanks for checking @true2thepen!
