### ISSUE TITLE
feature: Settings import/export tool

### ISSUE THREAD

**Issue by xitex** [nicumicle/simple-jwt-login#68]
## Is your feature request related to a problem?

Settings import/export tool 
## Describe the solution you'd like

To quickly set up the plugin, I would like to be able to export and import settings to the new site.
If you also add the option to generate a strong jwt key on import (optional), it will be just a holiday.
Thank you for amazing work!

**Comment by true2thepen** [comment]
I have a suggestion for this. Add an endpoint that allows one to pull the config to another install. You could have an import section under General that you put in credentials from the site you want to pull from and have the plugin pull the config and import it into the current site. This would keep from having to download an export and upload to import.

**Comment by nicumicle** [comment]
Thanks for the suggestion @true2thepen !!

I'm trying to build a system that will allow us to keep in "sync" multiple WordPress websitess.

We will need to do the changes only on the "master" website, and all the other websites will be able to automatically sync with it.

**Comment by nicumicle** [comment]
The new addon can be found here: https://github.com/simple-jwt-login/export-import
