### ISSUE TITLE
Edit the Force Login Link Wordings

### ISSUE THREAD

**Issue by lexicon2008** [nicumicle/simple-jwt-login#7]
I want assistance to edit the force login Link wordings

Eg. https://google.com/?**rest_route**=/maker/nice07544253652/**autologin**

how do I edit the words in asteriks in the link...
**rest_route** into something else
**autologin** into something else

Any assistance please?

**Comment by nicumicle** [comment]
Hello @lexicon2008,

You can create a Rewrite Rule to and then you can name this route as you want. 

The `?rest_route` parameter, comes from WordPress, and I don't think you can change that from the WordPress settings.

But, the autologin, you can change it from here: https://github.com/nicumicle/simple-jwt-login/blob/master/simple-jwt-login/src/Services/RouteService.php, line 9.
