### ISSUE TITLE
bug: Able to read protected endpoints with revoked tokens.

### ISSUE THREAD

**Issue by vagkalosynakis** [nicumicle/simple-jwt-login#75]
# Bug Report

## Plugin Version
Version 3.5.0

## PHP Version
PHP 8.0.27

## WordPress Version
Version 6.1.1

## Bug description

I am able to read protected endpoints using a revoked key by changed the header name. Steps to reproduce:

1. Protect and endpoint. (I used `/wp/v2/users`)
2. Make a GET request to verify it's protected
3. Login through the `/simple-jwt-login/v1/auth/login` endpoint to retrieve a token.
4. Revoke the token in `/simple-jwt-login/v1/auth/revoke` endpoint
5. Make sure that the token is invalid through the `/simple-jwt-login/v1/auth/validate` endpoint
6. Make a GET request to the protected endpoint using as a header: "JWT: [revoked token]" and verify it's still protected.
7. Change the Header KEY from `JWT` to `Authorization` but still send the revoked token
8. Endpoint is now able to be read with an invalid/revoked token.

The Invalid token should be disregarded completely and the endpoint should still be protected if the key is invalid.

## Other installed plugins (optional)

- Advanced Custom Fields PRO - Version 6.0.7
- WooCommerce - Version 7.3.0
- WP GraphQL - Version 1.13.7
- WP Mail SMTP - Version 3.7.0
- WP GraphQL CORS - Version 2.1
- WP GraphQL for ACF - 0.6.1

## Additional Context (optional)

**JWT is invalid**
![image](https://user-images.githubusercontent.com/31518958/219013477-800c3d24-9932-4651-be97-787c2c70f877.png)
_____
**`JWT` as a Header**
![image](https://user-images.githubusercontent.com/50824477/219009150-17fb531a-6919-4a06-be29-2a12fbb08864.png)
_____
**`Authorization` as a Header**
![image](https://user-images.githubusercontent.com/50824477/219009649-1bc285dc-872c-4db0-beac-8f5a21f9267a.png)

**Comment by CatchABus** [comment]
Is this bug still around? I'm planning to use this plugin and find this worrying.

**Comment by nicumicle** [comment]
Hi,
Sorry for my late response. The issue should be fixed now.
This [commit](https://github.com/nicumicle/simple-jwt-login/commit/fe8a3f2dbbc6ac7d4cd90e6438075b4ead34f933) is the fix.

Please download the plugin from https://simplejwtlogin.com/ and test to see if all works ok for you.
