### ISSUE TITLE
How to set token expirations based on User Role

### ISSUE THREAD

**Issue by mfs-bldmghty** [nicumicle/simple-jwt-login#77]
We want our Shop Manager JWTs to not expire at all. 

Customers would have the value set in the plugin's UI. 

I suspect there's a filter in the plugin that would help but nothing jumped out at me. 

Thanks

**Comment by nicumicle** [comment]
Hello,

You can use the [simple_jwt_login_jwt_payload_auth](https://simplejwtlogin.com/docs/hooks/#5-simple_jwt_login_jwt_payload_auth) filter.

This will allow you to change the payload on the auth endpoint.

In order for a **JWT** to **not expire**, you need to **remove** the `exp` parameter. Here you can see the payload parameters : [https://simplejwtlogin.com/docs/authentication/#jwt-payload-parameters](https://simplejwtlogin.com/docs/authentication/#jwt-payload-parameters)


Also, if you want to have access to the **currently authenticated user**, you can use the `simple_jwt_login_generate_payload` filter. Check the code [here](https://github.com/nicumicle/simple-jwt-login/blob/master/simple-jwt-login/src/Modules/SimpleJWTLoginHooks.php#L227).

Let me know if this helps.

**Comment by mfs-bldmghty** [comment]
@nicumicle  - OK. Great. Thank you.

**Comment by mfs-bldmghty** [comment]
Hey @nicumicle  - Can you confirm that the filter is working Version 3.5.0?

```
    add_filter( 'simple_jwt_login_jwt_payload_auth', __NAMESPACE__ . '\add_custom_jwt_payload', 10, 2 );

    function add_custom_jwt_payload( $payload, $request ){

        ray( $payload );
        ray( $request );

        return $payload;
    }
```

Spatie Ray doesn't dump anything so I presume I'm never even getting to that filter. Everything else seems to be working as expected, that is, we're able to auth, etc. Is there a particular type of request (?) we need to make of Simple JWT? Perhaps we're doing something wrong, and should be doing something else?
