### ISSUE TITLE
bug: Auto login doesn't work for first time

### ISSUE THREAD

**Issue by Fasih-Techx** [nicumicle/simple-jwt-login#80]
# Bug Report
The simple jwt login doesn't work with the URL for the first time it only works on the second try.
I tried to remove cookies and incognito mode but same issue.
## Plugin Version
Version 3.5.0

## PHP Version
Version 8.1

## WordPress Version
Version 6.2.2.2

## Bug description

**I want to auto-login and redirect the users to the home page without interacting with the wp-admin page.**

1. The JWT Login shows success in Postman when the redirect mode is none. even if you run the auto-login 1000 times. 

2. When I change the redirect mode in the settings from none to Dashboard and then run the auto login API it **redirects to the login page**, after that **if I run it again** it will log me in properly. (seems like the _cookies don't store_ on 1st attempt)
![image](https://github.com/nicumicle/simple-jwt-login/assets/88479141/9d1ce15b-654f-4657-b617-75d107d07cad)

4. When the redirect mode is changed to Homepage or Custom Url it shows **no cookies received** in postman. 
![image](https://github.com/nicumicle/simple-jwt-login/assets/88479141/f3676985-3429-4eab-bb47-b978cf175280)

My conclusion is most likely storing the cookies is not working when the wp-admin is not accessed prior to auto-login.

## Tets Credentials
you can test this on Postman. Settings for redirect is set to Homepage

**Authentication**

https://sheandhe.hakeem.ae/?rest_route=/simple-jwt-login/v1/auth&email=custompatient@hakeem.ae&password=custompatient@hakeem.ae&AUTH_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODUwMjcxMzQsImV4cCI6MTY4NTAzMDczNCwiZW1haWwiOiJjdXN0b21wYXRpZW50QGhha2VlbS5hZSIsImlkIjoiMjIiLCJzaXRlIjoiaHR0cHM6XC9cL3NoZWFuZGhlLmhha2VlbS5hZSIsInVzZXJuYW1lIjoiY3VzdG9tcGF0aWVudEBoYWtlZW0uYWUifQ.4QwlZDfIX40kprNgHW2TkTykzMLRKNCWipBiy1q6QiE

**Auto-Login**

https://sheandhe.hakeem.ae/?rest_route=/simple-jwt-login/v1/autologin&JWT=Jwt Code Here

##Hosting
Cloudways (with Cloudflare enterprise)
Cloudflare bot protection & DDos is On

## Other installed plugins 
Perfmatters
cloudways bot protection
Defender Pro

## Additional 
I tried to run all the above mention scenarios on Postman and Chrome incognito mode multiple times with all the plugins and Cloudflare enabled and after disabling Cloudflare and all other plugins the results are the same. However, I tried on my other website which is hosted on another Host auto-login working fine there without any issues. 

## Update
I tried some more testing and figured out that it's working on different hosts except Cloudways. I don't know how to deal with this because I tried to enable and disable different settings or cache etc.

**Comment by dani3l3** [comment]
You give very little information for the author or anyone to try and reproduce the issue... I have been using this for over a year and haven't got any trouble remotely similar to what you are describing... versions, detailed steps to reproduce would go a long way.

**Comment by Fasih-Techx** [comment]
Sorry, I didn't know before how this problem was happening or what was actually the problem. I run some tests and edited the description of the error. @dani3l3 Please let me know I this information is enough and if someone can help.

**Comment by Fasih-Techx** [comment]
Varnish Cache was the culprit. disabling it solved the problem
