### ISSUE TITLE
bug: Docs ”simple_jwt_login_before_endpoint“ hook example

### ISSUE THREAD

**Issue by hao97** [nicumicle/simple-jwt-login#83]
# Bug Report

## Plugin Version
3.50

## Bug description
Docs [[Examples](https://simplejwtlogin.com/docs/hooks/#code-examples)](https://simplejwtlogin.com/docs/hooks/#block-requests-on-auth-for-a-specific-email-address)
Block requests on /auth for a specific email address
`if ($method !== 'POST' && $endpoint !== 'auth') {
          return;
       }`
If $method = 'POST', `($method !== 'POST' && $endpoint !== 'auth')` will be false, it will pass through this code.
Maybe change to `($method !== 'POST' || $endpoint !== 'auth')` will be better

**Comment by nicumicle** [comment]
Hi @hao97 ,

The example is correct. We want to enable this hook only if the request method is `POST` on the `auth` endpoint.

This `if` is an early return.
 
```
if ($method !== 'POST' && $endpoint !== 'auth') { return; }
``` 
This means, that "**get out of this function is method is not POST and endpoint is not auth**".

In other words, the code will execute only if the method is POST and the endpoint is "auth".
