### ISSUE TITLE
bug: Meta data does not save in create use endpoint

### ISSUE THREAD

**Issue by diegoanvilla** [nicumicle/simple-jwt-login#86]
# Bug Report

## Plugin Version
3.5.1

## Bug description
When using the create user endpoint and adding the user_meta param the user is created but no meta user entry is creaed with the values provided

## Additional Context (optional)
Endoint example:
https://example.com/?rest_route=/simple-jwt-login/v1/users&email=test@test.com&user_login=test&AUTH_KEY=test&user_meta={"test":"test"}

**Comment by nicumicle** [comment]
Hi @diegoanvilla,

Thank you for reporting this bug. 
I've investigated this, and indeed, it seems to be an issue.

I'm working on a fix and come back with updates.

Best regards,
Nicu.

**Comment by nicumicle** [comment]
Hi @diegoanvilla ,
The issue should be fixed now.
 
Can you please download the plugin from https://github.com/nicumicle/simple-jwt-login/blob/master/download/simple-jwt-login.zip and check on your side if all works ok?

I recommend sending the request for register users in the body of the request with the `Content-Type: application/json`  header.

![image](https://github.com/nicumicle/simple-jwt-login/assets/20170987/51a52533-4b6a-4e0d-a2a4-98c8ea333b3d)


```shell

curl --location 'http://localhost:88/?rest_route=%2Fsimple-jwt-login%2Fv1%2Fusers' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "email@example.com",
    "password": "password",
    "user_meta": {
        "wp_user_level" : 123
    }
}'
```

PS: Please make sure you set the "Allowed user_meta keys on create user" in the Register user settings with the meta keys that you intend to use.
![image](https://github.com/nicumicle/simple-jwt-login/assets/20170987/9f0a4ba8-6ec6-4533-ac81-41ce3d3434f1)

**Comment by diegoanvilla** [comment]
Hi, yes the issue has been solved, thank you for the assistance :)
