### ISSUE TITLE
Can i have the jwt after the registration

### ISSUE THREAD

**Issue by williampractice1** [nicumicle/simple-jwt-login#9]
Hi nice plugin.
I was wondering if there is a way to get the jwt in the response of the registration endpoint, thanks a lot.
I am registering just with the email and checked the generation of a random password but i need to get the jwt for a mobile application, i am also checked the auto-login feature

**Comment by nicumicle** [comment]
Hello @williampractice1,

I just implemented the feature for allowing you to get the JWT on the register. 
Just go to the Register section, and enable this option:
![image](https://user-images.githubusercontent.com/20170987/134767865-1eba66a3-bcce-4de4-9d2e-c8e2b5dc3964.png)

Best regards,
Nicu.

**Comment by williampractice1** [comment]
Thank you so much great job bro
