### ISSUE TITLE
Add PR Welcome badge 

### ISSUE THREAD

**Issue by nicumicle** [nicumicle/simple-jwt-login#91]
Add  ![PR welcome](https://img.shields.io/badge/PRs-welcome-brightgreen) badge to the [readme](https://github.com/nicumicle/simple-jwt-login/blob/master/README.md)  file that links to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request.

**Comment by Tashuuuu** [comment]
I would like to work on it.
