### ISSUE TITLE
bug: Invalid email while register

### ISSUE THREAD

**Issue by techforeman** [nicumicle/simple-jwt-login#95]
# Bug Report

## Plugin Version
3.5.3

## PHP Version
8.1

## WordPress Version
6.4.2

## Bug description
It is not possible to create / register email when with '+' character. Adding such email manually on default user list it is possible.
name.surname+167@gmail.com

`/users&email=name.surname+167@gmail.com&user_login=599&first_name=test&last_name=test&password=NEW_USER_PASSWORD&AUTH_KEY=2321398`

**Comment by nicumicle** [comment]
Hi @techforeman ,

Thanks for reporting this bug.
Can you please try to send the parameters in the request body?
Here is an example: https://simplejwtlogin.com/docs/register-user/#examples

If you send the parameters as query params, the `+` will be translated to " "(space).

Let me know if this works for you or if you need help.

Best regards,
Nicu.
